version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "9025:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app1/build:/usr/share/nginx/html/app1
      - ./app2/build:/usr/share/nginx/html/app2
      - ./app3/build:/usr/share/nginx/html/app3
